version: 2

submodules:
  include: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: dirhtml
